### PR TITLE
Confirm box colored

### LINKED ISSUE #125: Make dialogs look awesome
See issue on Norton Commander color scheme / backdrop half shadows.  

The current dialog looks like:

image

I think we can do better:

https://github.com/gui-cs/Terminal.Gui/issues/2144

Note that my previous attempt at this was a failure: https://github.com/gui-cs/TerminalGuiDesigner/pull/111 but might have some salvageable code.

### PR DESCRIPTION
**Pull request by tznind**
Fixes  #125

Experimenting at improving readability of the warnings TerminalGuiDesigner produces.

Top is the current implementation (using `MessageBox.Query`).  Bottom is the one this PR introduces.  Its not perfect and I think more could maybe be done.  Leaving this as draft for now.

image

### CODE REVIEW

**Comment by BDisp** [comment]
I know why this is happening. As the dialog has focus he uses the focus color to clear. I'm trying to fix that for only the most focused is cleared. But I'm getting problems with the `TabView` which is calling the `base.Redraw` which is clearing part of `TabRowView`. But I'm trying fix it.

**Comment by tznind** [comment]
Are you talking about a problem with the top image or the bottom one? I deliberately set the background color to black for readability against the yellow but now I look at it again it does look bugged/wierd.  

Was just trying to spice up the message box and emphasize the message part.

**Comment by BDisp** [comment]
Sorry, I thought that was the resulting after your hack to workaround for the https://github.com/gui-cs/Terminal.Gui/issues/2094 issue. After the fix the dialog was using it's focus color scheme and was more or less like that :-)

**Comment by tznind** [comment]
Closing this as I don't think its an improvement

**Comment by tznind** [comment]
Here is the new revamp based on Norton Commander:

image

**Review by BDisp — APPROVED** [review]

**Pull request merged**
