### PR TITLE
Convert unit tests to NUnit 4.0

### PR DESCRIPTION
**Pull request by dodexahedron**
Opening this PR now, to provide easy tracking of work done on this back at the master repo.

This is not ready for merge at this time, though you are certainly free to merge whenever and as often as you like. I'll change this from draft status when the work is done.

### CODE REVIEW

**Comment by tznind** [comment]
Hey sorry for this, looks like it closed when I merged `v2_latest_changes_pre_220`

Can you please re-open and target `v2` branch? This is great work!

**Comment by tznind** [comment]
Cool, let me know when it is ready <3

**Comment by dodexahedron** [comment]
Opening up a new one, shortly.
Lots more improvements since the last one.

This one includes some commits under the src folder, mostly for formalizing a couple of things and also for adding new stuff, as part of a gradual process to eliminate some reflection, where possible.

A lot of tests have been unrolled into unique cases, and some tests are much more thorough, now (especially in the CodeDomArgsTests class).

All tests pass, and the tested cases are a superset of cases that were previously tested.

I would suggest not merging, yet, as I have some incomplete in-progress modifications happening to the github workflows to make them leaner and give us better control over them. We should probably chat about that stuff at some point, too, to be sure the final behavior is as desired.

**Comment by dodexahedron** [comment]
Here ya go

Opened #260

**Pull request closed without merging**
