### PR TITLE
Migrate to nunit 4

### PR DESCRIPTION
**Pull request by dodexahedron**
This includes the changes necessary to make the unit tests compile against NUnit 4.0.

I converted one set of tests to the Constraint style, as an example.

The rest I simply switched to the ClassicAssert class, which is the new location of all of the old assert methods.

No functional changes were made to any tests.

This supersedes #252 opened by Dependabot.\
This also includes the changes from #255, which I opened a little while ago (this branch is branched from that commit).

### CODE REVIEW

**Comment by dodexahedron** [comment]
I went ahead and converted a few more tests, just to demonstrate more concepts in the somewhat more complex test cases in BorderColorTests, over properties of collections and such. 🤷‍♂️

**Comment by tznind** [comment]
Great stuff, I will try and port this to the `v2` branch too (for supporting Terminal.Gui 2.0.0)

**Comment by tznind** [comment]
`v2` now has latest dependency too 505305bdd5f0b49cd126d076e45c0d1d081a23ee 

I didn't merge directly since test cases have diverted in updating Terminal.Gui 1 to 2 version compatibility so am missing some of the `Assert..That` goodness (see [v2.x Breaking Change Thread](https://github.com/gui-cs/Terminal.Gui/discussions/2448)).  But I will start using that now in the v2 branch which is where I am focusing effort at the moment <3 .

**Comment by dodexahedron** [comment]
Ah ok.

I just converted another test class in v1 on my same branch as was in the PR.

Don't bother with it, though. I'll branch from your v2 work and do future work in there instead. If the changes I made to that test class still apply in v2, I'll merge them over, but, if not, it was only like 15 minutes, so no biggie. :)

I had a feeling I probably should have focused on v2 from the start, but I didn't listen to myself, so my bad. 😅

**Pull request merged**
