### PR TITLE
ScrollView designer support

### LINKED ISSUE #114: What is required to add designer support for ScrollView
To use `ScrollView` you must set `ContentSize`.  Editor support will require:

- [ ] A designer for `Size` struct
- [ ] A sensible default in `ViewFactory`
- [ ] Possibly some drag and drop adjustment so that when dropping controls into the `ScrollView` when it is scrolled down works.
- [ ] Code generation for `Size` (`ContentSize`)
- [ ] All the tests
- [ ] A way to drag and resize the view when it doesn't have any borders (already solved in #106)

Here is the minimum code to produce a ScrollView.  Setting `ContentSize` is absolutely vital.  Without it stuff just doesn't work properly.

```csharp
using Terminal.Gui;

Application.Init();
var win = new Window("Example App (Ctrl+Q to quit)");

var scr = new ScrollView()
{
    Width = Dim.Fill(),
    Height = Dim.Fill(),
    ShowVerticalScrollIndicator = true
};
scr.ContentSize = new Size(30, 500);
scr.Add(new BigView());

win.Add(scr);
Application.Run(win);
Application.Shutdown();

class BigView : View
{
    public BigView()
    {
        Height = 500;
        Width = 30;
    }
    public override void Redraw(Rect bounds)
    {
        base.Redraw(bounds);

        for(int x=0;x<30;x++)
        {
            for (int y = 0; y < 500; y++)
            {
                var digit = y % 10;
                AddRune(x, y, digit.ToString()[0]);
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by tznind**
Fixes #114 

scrollview

Example code generated
```csharp
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace YourNamespace {
    using System;
    using Terminal.Gui;
    
    
    public partial class MoreViews : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ScrollView scrollview1;
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.Label label2;
        
        private void InitializeComponent() {
            this.label2 = new Terminal.Gui.Label();
            this.label1 = new Terminal.Gui.Label();
            this.scrollview1 = new Terminal.Gui.ScrollView();
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.scrollview1.Width = 11;
            this.scrollview1.Height = 5;
            this.scrollview1.X = 0;
            this.scrollview1.Y = 0;
            this.scrollview1.ContentSize = new Size(40,10);
            this.scrollview1.Data = "scrollview1";
            this.scrollview1.Text = "";
            this.scrollview1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.scrollview1);
            this.label1.Width = 4;
            this.label1.Height = 1;
            this.label1.X = 1;
            this.label1.Y = 6;
            this.label1.Data = "label1";
            this.label1.Text = "Heya";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.scrollview1.Add(this.label1);
            this.label2.Width = 4;
            this.label2.Height = 1;
            this.label2.X = Pos.AnchorEnd(1);
            this.label2.Y = Pos.AnchorEnd(1);
            this.label2.Data = "label2";
            this.label2.Text = "End";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.scrollview1.Add(this.label2);
        }
    }
}

```

### CODE REVIEW

**Comment by tznind** [comment]
Seems to be a wierd issue where on reloading the dialog the contents don't render till you press `End` or other keystrokes

**Comment by BDisp** [comment]
It´s loading fine to me. Here my designer. I set the `End` label `X` to `AnchorEnd(3`) and `Y` to `AnchorEnd(1)`. Another weird situation I'm seen in your video is the `ContextMenu` background color which is blue. May be you used on some branch that you have that feature.

```cs
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace YourNamespace {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyView : Terminal.Gui.Window {
        
        private Terminal.Gui.ScrollView scrollview1;
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.Label label2;
        
        private void InitializeComponent() {
            this.label2 = new Terminal.Gui.Label();
            this.label1 = new Terminal.Gui.Label();
            this.scrollview1 = new Terminal.Gui.ScrollView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.scrollview1.Width = 18;
            this.scrollview1.Height = 7;
            this.scrollview1.X = 0;
            this.scrollview1.Y = 0;
            this.scrollview1.ContentSize = new Size(20,10);
            this.scrollview1.Data = "scrollview1";
            this.scrollview1.Text = "";
            this.scrollview1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.scrollview1);
            this.label1.Width = 4;
            this.label1.Height = 1;
            this.label1.X = 0;
            this.label1.Y = 0;
            this.label1.Data = "label1";
            this.label1.Text = "Heya";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.scrollview1.Add(this.label1);
            this.label2.Width = 3;
            this.label2.Height = 1;
            this.label2.X = Pos.AnchorEnd(3);
            this.label2.Y = Pos.AnchorEnd(1);
            this.label2.Data = "label2";
            this.label2.Text = "End";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.scrollview1.Add(this.label2);
        }
    }
}

```

**Comment by BDisp** [comment]
@tznind I also remember that you can use the `MDI` containers in the `Terminal.Application` allowing having various opens windows which can be used as properties, toolbox or whatever you want.

**Review by BDisp — APPROVED** [review]

**Comment by tznind** [comment]
Cool, I'll get this merged then.  Don't worry about the colors, think it is just gif compression.  I have started setting some options like 'color table' in the gif app I use to reduce gif size (that one is like 500kb despite being very long).

**Comment by BDisp** [comment]
> @tznind I also remember that you can use the `MDI` containers in the `Terminal.Application` allowing having various opens windows which can be used as properties, toolbox or whatever you want.

And you may make available to the user start creating a `MDI` container app instead of `Window` or `Dialog` as well.

**Comment by tznind** [comment]
Yeah MDI stuff might get complicated, one for the todo list I think.  Want to get all the regular controls working really slick first.

**Pull request merged**
