### PR TITLE
Save improvements

### LINKED ISSUE #36: Warn on unsaved changes
If user exits with Ctrl+Q warn the user if there are unsaved changes.

We can probably look at the undo stack size for that.  Track it on save and watch for changes

### PR DESCRIPTION
**Pull request by tznind**
image

Fixes #36

### CODE REVIEW

**Comment by BDisp** [comment]
Sometimes I receive this error. I think it's related with `Pos/Dim`. What I do was setting the a `TextField.X` to the `Label.Right`. Closing the tool and reopen it doesn't throws any exception. But if I move the label down/right and save, when I reopen it throw the follow exception.

```
Failed to open 'MyView.Designer.cs'
One or more errors occurred. (Could not create instance of YourNamespace.MyV
iew)

Could not create instance of YourNamespace.MyView
   at TerminalGuiDesigner.FromCode.CodeToView.CreateInstance() in E:\Repos\C
Sharp\gui-cs\TerminalGuiDesigner\src\FromCode\CodeToView.cs:line 88
   at TerminalGuiDesigner.UI.Editor.<>c__DisplayClass33_0.<Open>b__0() in E:
\Repos\CSharp\gui-cs\TerminalGuiDesigner\src\UI\Editor.cs:line 726
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread
 threadPoolThread, ExecutionContext executionContext, ContextCallback callba
ck, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread
 threadPoolThread, ExecutionContext executionContext, ContextCallback callba
ck, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSl
ot, Thread threadPoolThread)
Exception has been thrown by the target of an invocation.
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boole
an wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean 
wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at TerminalGuiDesigner.FromCode.CodeToView.CreateInstance() in E:\Repos\C
Sharp\gui-cs\TerminalGuiDesigner\src\FromCode\CodeToView.cs:line 83
Object reference not set to an instance of an object.
   at Terminal.Gui.Pos.PosView.ToString()
   at Terminal.Gui.Pos.PosCombine.ToString()
   at Terminal.Gui.Pos.PosCombine.ToString()
   at Terminal.Gui.Pos.SetPosCombine(Pos left, PosCombine newPos)
   at Terminal.Gui.Pos.op_Addition(Pos left, Pos right)
   at YourNamespace.MyView.InitializeComponent()
   at YourNamespace.MyView..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boole
an wrapExceptions)
```

**Comment by BDisp** [comment]
Another think Ctrl+O in the Windows Terminal doesn't work so I changed to open the Console Windows Host when I run the tool.

**Comment by BDisp** [comment]
FYI in the end of the Initialize method of the `View` class two virtual methods are called, the `UpdateTextFormatterText` and the `ProcessResizeView`. The `Button` and the `Checkbox` views use these methods to proper initialize only after the `View` is initialized. Is here where a view want to know if a `Pos/Dim` is already sets. You can use both or one of them to manage the necessary definitions when a new view is added.

**Review by BDisp — APPROVED** [review]

**Comment by tznind** [comment]
> Another think Ctrl+O in the Windows Terminal doesn't work so I changed to open the Console Windows Host when I run the tool.

Cool, there is keybinding support but it requires copying/creating/editing a `Keys.yaml` file (which has to be in the current directory too).

There is a ticket to provide UI support for keybinding https://github.com/gui-cs/TerminalGuiDesigner/issues/37 I will get to that.  I will probably rework the current system to use a single user settings file in user appdata/home dir.  Especially since the `Keys.yaml` file is becoming more of a general settings file I will probably a quite deep refactor on that area of the program.

**Comment by tznind** [comment]
> FYI in the end of the Initialize method of the `View` class two virtual methods are called, the `UpdateTextFormatterText` and the `ProcessResizeView`. The `Button` and the `Checkbox` views use these methods to proper initialize only after the `View` is initialized. Is here where a view want to know if a `Pos/Dim` is already sets. You can use both or one of them to manage the necessary definitions when a new view is added.

Thanks for this guidance,  I'm not sure I fully follow this.  Are you able to open a new issue and describe what is wrong or could be done better in the current handling of checkbox/button?

Or if your comment is related to the PosRelative stuff then I think the root cause is probably https://github.com/gui-cs/TerminalGuiDesigner/issues/60

**Comment by tznind** [comment]
> FYI in the end of the Initialize method of the `View` class two virtual methods are called, the `UpdateTextFormatterText` and the `ProcessResizeView`. The `Button` and the `Checkbox` views use these methods to proper initialize only after the `View` is initialized. Is here where a view want to know if a `Pos/Dim` is already sets. You can use both or one of them to manage the necessary definitions when a new view is added.

Thanks for this guidance,  I'm not sure I fully follow this.  Are you able to open a new issue and describe what is wrong or could be done better in the current handling of checkbox/button?

Or if your comment is related to the PosRelative stuff then I think the root cause is probably https://github.com/gui-cs/TerminalGuiDesigner/issues/60

**Comment by BDisp** [comment]
> Or if your comment is related to the PosRelative stuff then I think the root cause is probably #60

Yes, is relative to this. I was referring where you control the loading of the views and check if all the PosRelative/DimRelative are already handled before setting.

**Pull request merged**
