### PR TITLE
V2

### PR DESCRIPTION
**Pull request by tznind**
Terminal.Gui is preparing for a v2 release.

In order for the designer to be ready and compatible with the new APIs I have created this branch.

This PR adds a git submodule that targets `v2_develop` instead of the current v1 Nuget package

Tasks are:
- [x] Add git submodule targeting v2_develop branch of Terminal.Gui
- [x] Fix breaking changes in the editor codebase
- [x] Fix editor code generation that is no longer correctl (e.g. `TableView` code gen)
- [x] Fix tests
- [x] Test extensively
- [x] Remove submodule and target Nuget package 2.0 (when shipped)
- [ ] Ship an alpha release

Feature Tasks:
- [x] Support SpinnerView
- [ ] Support TileView

### CODE REVIEW

**Comment by tig** [comment]
@tznind I know you said you'll be out for a while, but if you see this can you give me a quick summary of the status of TGD for v2?

Is there anything I can do to help?

**Comment by tznind** [comment]
We are in pretty good place

I periodically update to latest nuget package and fix all breaking changes.

Most recent was upgrade to [2.0.0-pre.149](https://github.com/gui-cs/TerminalGuiDesigner/pull/289)

There are more breaking changes since then I am tackling in

https://github.com/gui-cs/TerminalGuiDesigner/pull/292

You can see that PR description for what needs fixed 

In terms of non-breaking functionality, we have lost support for the FrameView because drag/move doesn't work properly.

Borders are disabled for now I think

But most of the rest is functional from memory

A while ago I wrote [nfirestore-cli](https://github.com/tznind/nfirestore-cli) primarily as a way of testing out v2 designer and it worked okay.

But to use TGD you need to stick to the exact nuget package v2 references and updating with TGD 'lock step' requires manual updates to .Designer.cs files.  This is to be expected because pre alpha=breaking changes.

There is definitely room to help! I need to dig deeper when I get home to identify best areas also to do a more in depth review of what is missing.

**Comment by tig** [comment]
Please use this release as your new starting point: https://www.nuget.org/packages/Terminal.Gui/2.0.0-prealpha.216

**Comment by tznind** [comment]
Closing because v2 is now live and v2 is the default branch

**Pull request closed without merging**
