### PR TITLE
Double click activate

### PR DESCRIPTION
**Pull request by tznind**
User can now double click to select an item anwyhere they are asked to make a choice for a single object.

image

### CODE REVIEW

**Comment by tznind** [comment]
Are you able to post the contents of the .Designer.cs file that you coun't open? that would really help diagnose how it is outputting bad code?

**Comment by BDisp** [comment]
> Are you able to post the contents of the .Designer.cs file that you coun't open? that would really help diagnose how it is outputting bad code?


```
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.16.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace YourNamespace {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyView : Terminal.Gui.Window {
        
        private Terminal.Gui.TextField textfield1;
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.TableView tableview1;
        
        private void InitializeComponent() {
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.textfield1 = new Terminal.Gui.TextField();
            this.textfield1.Width = 4;
            this.textfield1.Height = 1;
            this.textfield1.X = Pos.Right(label1) + 1;
            this.textfield1.Y = 0;
            this.textfield1.Secret = false;
            this.textfield1.Data = "textfield1";
            this.textfield1.Text = "Heya";
            this.textfield1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textfield1);
            this.label1 = new Terminal.Gui.Label();
            this.label1.Width = 4;
            this.label1.Height = 1;
            this.label1.X = 69;
            this.label1.Y = 14;
            this.label1.Data = "label1";
            this.label1.Text = "Heya";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1);
            this.tableview1 = new Terminal.Gui.TableView();
            this.tableview1.Width = 50;
            this.tableview1.Height = 5;
            this.tableview1.X = 62;
            this.tableview1.Y = 25;
            this.tableview1.Data = "tableview1";
            this.tableview1.Text = "";
            this.tableview1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.tableview1.FullRowSelect = false;
            this.tableview1.Style.AlwaysShowHeaders = false;
            this.tableview1.Style.ExpandLastColumn = true;
            this.tableview1.Style.InvertSelectedCellFirstCharacter = false;
            this.tableview1.Style.ShowHorizontalHeaderOverline = true;
            this.tableview1.Style.ShowHorizontalHeaderUnderline = true;
            this.tableview1.Style.ShowVerticalCellLines = true;
            this.tableview1.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable tableview1Table;
            tableview1Table = new System.Data.DataTable();
            System.Data.DataColumn tableview1TableColumn0;
            tableview1TableColumn0 = new System.Data.DataColumn();
            tableview1TableColumn0.ColumnName = "Column 0";
            tableview1Table.Columns.Add(tableview1TableColumn0);
            System.Data.DataColumn tableview1TableColumn1;
            tableview1TableColumn1 = new System.Data.DataColumn();
            tableview1TableColumn1.ColumnName = "Column 1";
            tableview1Table.Columns.Add(tableview1TableColumn1);
            System.Data.DataColumn tableview1TableColumn2;
            tableview1TableColumn2 = new System.Data.DataColumn();
            tableview1TableColumn2.ColumnName = "Column 2";
            tableview1Table.Columns.Add(tableview1TableColumn2);
            System.Data.DataColumn tableview1TableColumn3;
            tableview1TableColumn3 = new System.Data.DataColumn();
            tableview1TableColumn3.ColumnName = "Column 3";
            tableview1Table.Columns.Add(tableview1TableColumn3);
            this.tableview1.Table = tableview1Table;
            this.Add(this.tableview1);
        }
    }
}

```

**Comment by tznind** [comment]
Looks like maybe you dont have this PR merged into the branch that saved this #59 the constructor calls are not at the start of InitializeComponent

**Comment by BDisp** [comment]
> Looks like maybe you dont have this PR merged into the branch that saved this #59 the constructor calls are not at the start of InitializeComponent

Yes I have the main branch up to date and this pr has the #59, but still get the error.

imagem

**Comment by tznind** [comment]
Did you have #59 when you saved the file though?

**Comment by BDisp** [comment]
> Did you have https://github.com/gui-cs/TerminalGuiDesigner/pull/59 when you saved the file though?

Ah that might be the reason. Sorry. Thanks.

**Comment by BDisp** [comment]
Sorry @tznind I'm still having this error. This is only a `Label` and  `TextField`. The `TextField.X` is relative to the `Label.Right` with a offset of 1. Then I move by mouse the `Label` down and right. Saved and closed. When reopening it I get the above mentioned error.

imagem

**Comment by tznind** [comment]
> Sorry @tznind I'm still having this error. This is only a `Label` and `TextField`. The `TextField.X` is relative to the `Label.Right` with a offset of 1. Then I move by mouse the `Label` down and right. Saved and closed. When reopening it I get the above mentioned error.

Ah my bad, I had not merged #61 and quoted the wrong PR for the fix.  I've now merged the correct PR.  main should work now.

**Comment by BDisp** [comment]
> > Sorry @tznind I'm still having this error. This is only a `Label` and `TextField`. The `TextField.X` is relative to the `Label.Right` with a offset of 1. Then I move by mouse the `Label` down and right. Saved and closed. When reopening it I get the above mentioned error.
> 
> Ah my bad, I had not merged #61 and quoted the wrong PR for the fix. I've now merged the correct PR. main should work now.

But I merged main into this pr and still having the error.

**Comment by tznind** [comment]
Yes.  The fix was sitting in #61 which was not yet merged into main.  I merged it 1 minute ago so main should *now* be fixed

**Comment by BDisp** [comment]
Thanks, it's fixed now. I made the same mistake when I used this pr by not delete the .Designer.cs first. Good work and thanks for your patience :-)

**Comment by tznind** [comment]
No problem, thanks for persisting or I would probably have forgotten about that PR for a lot longer :fearful:

**Pull request merged**
